# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9753e88a1ca38acb7df04d41ce81c2b5fcd1ec9df29e9592a8b186b2ee5aa54b0be2feb3eee65edf0a1f636a96fae427955eb80aa1fbfb0d4426510a3e582814

test:
  secret_key_base: 3c4e1aab77d6fb0edbe949e33b61963456d522117ddb33d79a5d41457224dde7f530e7f6f1612f0452be399bcbe74c550f6ecadd3188d71e0b17980f1bde8fd0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
